{
    "addressLookupTaskURL" : "https://maps.charlescountymd.gov/arcgis/rest/services/DPWUtilities/InforAddressLookup/GPServer/InforAddressLookup",
    "inforFeatureClassNames" : [
          "wExerciseSystemValves", 
          "rSystemValve", 
          "rControlValves", 
          "rManhole", 
          "rNetworkStructure", 
          "rHydrant", 
          "rLateralLine", 
          "rReclaimedLine", 
          "rWaterStructure", 
          "wMeter", 
          "wCurbStop", 
          "wSamplingStation", 
          "wNetworkStructure", 
          "wHydrant", 
          "wHydrant", 
          "wHydrant Abandoned", 
          "wControlValve", 
          "wSystemValve", 
          "wSystemValve Abandoned", 
          "wSpatialOperationsRecord", 
          "wScadaSensor", 
          "wPressurizedMain", 
          "wPressurizedMain - Low Accuracy", 
          "wPressurizedMain Abandoned", 
          "wLateralLine", 
          "CHARLES.wLateralLinePrivate", 
          "wThrustProtection",   
          "wPressurizedMain .75//", 
          "wPressurizedMain 1//", 
          "wPressurizedMain 1.25//", 
          "wPressurizedMain 1.5//", 
          "wPressurizedMain 2//", 
          "wPressurizedMain 2.5//", 
          "wPressurizedMain 3//", 
          "wPressurizedMain 4//", 
          "wPressurizedMain 6//", 
          "wPressurizedMain 8//", 
          "wPressurizedMain 10//", 
          "wPressurizedMain 12//", 
          "wPressurizedMain 14//", 
          "wPressurizedMain 16//", 
          "wPressurizedMain Unk", 
          "wDualCheckFire", 
          "wDualCheckDomestic", 
          "Clean Out", 
          "Discharge Point", 
          "Pump", 
          "System Valve", 
          "Manhole", 
          "Manhole Labels", 
          "Manhole Abandoned", 
          "Network Structure", 
          "Network Structure", 
          "Network Structure Abandoned", 
          "Spatial Operations Record", 
          "Scada Sensor", 
          "Anode", 
          "Pressurized Main", 
          "Pressurized Main", 
          "Pressurized Main Label", 
          "Pressurized Main Abandoned", 
          "Lateral Line", 
          "Lateral Line Abandoned", 
          "Lateral Line Private", 
          "Gravity Main", 
          "Gravity Main Labels", 
          "Gravity Main", 
          "Gravity Main Low Accuracy", 
          "Gravity Main Abandoned", 
          "Underground Enclosure", 
          "Thrust Protection", 
          "Water Structure"
    ],
    "inforAssetTypes" : [
        {"type":"wExerciseSystemValves", "value": "wExerciseSystemValves"},
        {"type":"rSystemValve", "value": "rSystemValve"},
        {"type":"rControlValves", "value": "rControlValves"},
        {"type":"rManhole", "value": "rManhole"},
        {"type":"rNetworkStructure", "value": "rNetworkStructure"},
        {"type":"rHydrant", "value": "rHydrant"},
        {"type":"rLateralLine", "value": "rLateralLine"},
        {"type":"rReclaimedLine", "value": "rReclaimedLine"},
        {"type":"rWaterStructure", "value": "rWaterStructure"},
        {"type":"wMeter", "value": "wMeter"},
        {"type":"wCurbStop", "value": "wCurbStop"},
        {"type":"wSamplingStation", "value": "wSamplingStation"},
        {"type":"wNetworkStructure", "value": "wNetworkStructure"},
        {"type":"wHydrant", "value": "wHydrant"},
        {"type":"wHydrant", "value": "wHydrant"},
        {"type":"wHydrant Abandoned", "value": "wHydrant Abandoned"},
        {"type":"wControlValve", "value": "wControlValve"},
        {"type":"wSystemValve", "value": "wSystemValve"},
        {"type":"wSystemValve Abandoned", "value": "wSystemValve Abandoned"},
        {"type":"wSpatialOperationsRecord", "value": "wSpatialOperationsRecord"},
        {"type":"wScadaSensor", "value": "wScadaSensor"},
        {"type":"wPressurizedMain", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain - Low Accuracy", "value": "wPressurizedMain - Low Accuracy"},
        {"type":"wPressurizedMain Abandoned", "value": "wPressurizedMain Abandoned"},
        {"type":"wLateralLine", "value": "wLateralLine"},
        {"type":"CHARLES.wLateralLinePrivate", "value": "CHARLES.wLateralLinePrivate"},
        {"type":"wThrustProtection  ", "value": "wThrustProtection"},
        {"type":"wPressurizedMain .75", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 1", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 1.25", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 1.5", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 2", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 2.5", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 3", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 4", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 6", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 8", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 10", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 12", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 14", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain 16", "value": "wPressurizedMain"},
        {"type":"wPressurizedMain Unk", "value": "wPressurizedMain"},
        {"type":"wDualCheckFire", "value": "wDualCheckFire"},
        {"type":"wDualCheckDomestic", "value": "wDualCheckDomestic"},
        {"type":"Clean Out", "value": "Clean Out"},
        {"type":"Discharge Point", "value": "Discharge Point"},
        {"type":"Pump", "value": "Pump"},
        {"type":"System Valve", "value": "System Valve"},
        {"type":"Manhole", "value": "Manhole"},
        {"type":"Manhole Labels", "value": "Manhole Labels"},
        {"type":"Manhole Abandoned", "value": "Manhole Abandoned"},
        {"type":"Network Structure", "value": "Network Structure"},
        {"type":"Network Structure", "value": "Network Structure"},
        {"type":"Network Structure Abandoned", "value": "Network Structure Abandoned"},
        {"type":"Spatial Operations Record", "value": "Spatial Operations Record"},
        {"type":"Scada Sensor", "value": "Scada Sensor"},
        {"type":"Anode", "value": "Anode"},
        {"type":"Pressurized Main", "value": "Pressurized Main"},
        {"type":"Pressurized Main", "value": "Pressurized Main"},
        {"type":"Pressurized Main Label", "value": "Pressurized Main Label"},
        {"type":"Pressurized Main Abandoned", "value": "Pressurized Main Abandoned"},
        {"type":"Lateral Line", "value": "Lateral Line"},
        {"type":"Lateral Line Abandoned", "value": "Lateral Line Abandoned"},
        {"type":"Lateral Line Private", "value": "Lateral Line Private"},
        {"type":"Gravity Main", "value": "Gravity Main"},
        {"type":"Gravity Main Labels", "value": "Gravity Main"},
        {"type":"Gravity Main", "value": "Gravity Main"},
        {"type":"Gravity Main Low Accuracy", "value": "Gravity Main"},
        {"type":"Gravity Main Abandoned", "value": "Gravity Main"},
        {"type":"Underground Enclosure", "value": "Underground Enclosure"},
        {"type":"Thrust Protection", "value": "Thrust Protection"},
        {"type":"Water Structure", "value": "Water Structure"}
        ],
    "inforClassTypes" : [
        {"class":"--Select Workorder Class--", "code":"NULL", "disabled": "disabled"},
        {"class":"Air In Lines", "code":"AIL"},
        {"class":"Black rings on toilet", "code":"BR"},
        {"class":"Bring clean out cap to ground level", "code":"CGL"},
        {"class":"Broken Pipe", "code":"BP"},
        {"class":"Broken waste tank", "code":"BWT"},
        {"class":"Brown Water", "code":"BW"},
        {"class":"Camera sewer main line", "code":"CSML"},
        {"class":"Camera sewer service", "code":"CSS"},
        {"class":"Cap Replacement", "code":"CR"},
        {"class":"Check for hit wires", "code":"CHW"},
        {"class":"Clean out repair", "code":"COR"},
        {"class":"Curb Box Repair", "code":"CBR"},
        {"class":"Curb stop repair", "code":"CS"},
        {"class":"Cut Pipes To Ground Level", "code":"CP"},
        {"class":"Drain Backup", "code":"DB"},
        {"class":"Driveway Sunk In", "code":"DSI"},
        {"class":"Fire Hydrant Hit", "code":"FHH"},
        {"class":"Fire Hydrant Leaking", "code":"FHL"},
        {"class":"Fire Hydrant Out Of Service", "code":"FHOS"},
        {"class":"Holding Tank", "code":"HT"},
        {"class":"Hydrant Flow test", "code":"HFT"},
        {"class":"Hydrant valve repair", "code":"HV"},
        {"class":"Install Clean Out", "code":"ICO"},
        {"class":"Landscaping", "code":"LNDS"},
        {"class":"Low Water Pressure", "code":"LWP"},
        {"class":"Main line valve repair", "code":"MV"},
        {"class":"Manhole Cover Missing", "code":"MCM"},
        {"class":"Manhole Leaking", "code":"ML"},
        {"class":"Needs access to water tank", "code":"AWT"},
        {"class":"No Water", "code":"NW"},
        {"class":"Orange water", "code":"OW"},
        {"class":"Other - See comments for details", "code":"OTH"},
        {"class":"Pipe out of ground", "code":"POG"},
        {"class":"Pipes Leaking", "code":"PL"},
        {"class":"Road Repair", "code":"RR"},
        {"class":"Sand in Water", "code":"SIW"},
        {"class":"Sanitary sewer overflow", "code":"SSO"},
        {"class":"Sewer Alarm Light Going Off And/Or Sounding", "code":"SA"},
        {"class":"Sewer Back Up", "code":"SBU"},
        {"class":"Sewer backups - not sewer storm drain", "code":"SBU4"},
        {"class":"Sewer backups into a basement that are the County's responsibility", "code":"SBU3"},
        {"class":"Sewer backups/spill that are not the County's responsibility", "code":"SBU1"},
        {"class":"Sewer backups/spill that are the County's responsibility", "code":"SBU2"},
        {"class":"Sewer main cleaning", "code":"SMC"},
        {"class":"Sewer Overflow", "code":"SO"},
        {"class":"Sidewalk repair", "code":"SWR"},
        {"class":"Sink Hole", "code":"SH"},
        {"class":"Smelly Water", "code":"SW"},
        {"class":"Snow removal", "code":"SR"},
        {"class":"Turn on Water", "code":"TW"},
        {"class":"Water in water meter", "code":"WMW"},
        {"class":"Water Leak", "code":"WL"},
        {"class":"Water Main Break", "code":"WMB"},
        {"class":"Water meter needs repair", "code":"WMR"},
        {"class":"Water Shut Off", "code":"WSO"},
        {"class":"Well Overflowing", "code":"WO"},
        {"class":"Wet well cleaning", "code":"WWC"},
        {"class":"White Water", "code":"WW"},
        {"class":"Yard Repair", "code":"YR"},
        {"class":"Yellow Water", "code":"YW"}
    ],
    "boolean": true,
    "null": null,
    "number": 123,
    "object": {
        "a": "b",
        "c": "d",
        "e": "f"
    },
  "string": "Hello World"
}