
{
    "identifier": "OBJECTID",
    "label": "NAME",
    "items": [
    { "OBJECTID": "1", "name": "Swan Point" },
    { "OBJECTID": "321", "name": "Mattawoman Treatment Facility" },
    { "OBJECTID": "322", "name": "Strawberry Hills" },
    { "OBJECTID": "323", "name": "Zekiah" },
    { "OBJECTID": "324", "name": "Unknown" },
    { "OBJECTID": "325", "name": "North Point" },
    { "OBJECTID": "326", "name": "Bryans Road" },
    { "OBJECTID": "327", "name": "Pinefield" },
    { "OBJECTID": "328", "name": "Unknown 2" },
    { "OBJECTID": "329", "name": "Laurel Branch 3" },
    { "OBJECTID": "330", "name": "Indian Head Manor" },
    { "OBJECTID": "331", "name": "Eutaw Forest" },
    { "OBJECTID": "332", "name": "Ryon Woods" },
    { "OBJECTID": "333", "name": "Brawner Estates" },
    { "OBJECTID": "334", "name": "Brentwood" },
    { "OBJECTID": "335", "name": "Laurel Acres" },
    { "OBJECTID": "336", "name": "St Marks" },
    { "OBJECTID": "337", "name": "Rt 5" },
    { "OBJECTID": "338", "name": "Pomonkey" },
    { "OBJECTID": "339", "name": "Green Haven" },
    { "OBJECTID": "340", "name": "Dorchester Circle" },
    { "OBJECTID": "342", "name": "Rt 925B" },
    { "OBJECTID": "343", "name": "White Plains CC" },
    { "OBJECTID": "344", "name": "Southwinds" },
    { "OBJECTID": "345", "name": "DeMarr Rd" },
    { "OBJECTID": "347", "name": "St Charles 5A" },
    { "OBJECTID": "348", "name": "White Plains Park" },
    { "OBJECTID": "349", "name": "Wakefield" },
    { "OBJECTID": "350", "name": "Potomac Heights" },
    { "OBJECTID": "351", "name": "Montgomery Lane" },
    { "OBJECTID": "346", "name": "St Charles 3A" },
    { "OBJECTID": "341", "name": "St Charles 2A" }
]
}